### ISSUE TITLE
Forge/PmlCorruption beta8b

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#10]
this occured only in beta 8b and once in beta 8c? . the last time I had a corruption crash was when forge was fully working and when I added the seasons mod i got 1 of ten crashes but, here is the only one I documented. I AM UNSURE IF THIS IS A CURRENTLY STANDING BUG AND MIGHT HAVE HAD TO DO WITH MC LAUNCHER FORGE BUT, THE VERY LAST TIME I GOT THIS IT WAS lagitament 
http://pastebin.com/yRkYiB1V

**Comment by PitchBright** [comment]
If it doesn't exist in 8d, then it's no longer a problem. This can be closed.

**Comment by jredfox** [comment]
yeh keep it closed it no longer exsists I just wanted to report this incase it happens again.

**Comment by TheWeatherPony** [comment]
@PitchBright 8d has not been finalized yet, and may become 9 before it is ready. Current live private version is 8c4.

**Comment by PitchBright** [comment]
either way… stacktrace tells him the problem:

java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:230)
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
at Config.getWorldServer(Config.java:1746)
**at RandomMobs.entityLoaded(RandomMobs.java:49)**
