### ISSUE TITLE
Request: Configurable Snow Heights 1.7.10 .json

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#103]
Version: [1.7.10]TheSeasonsMod-pre-3.0beta13d5 

I don't see it generating any configurations for snow stack height even though #40 you were going to add it per season per biome?  So I guess when you implament #40 I would also like that to be configurable via .json as well

**I would love this feature for realisticraft and biome mods**

**Comment by TheWeatherPony** [comment]
It is there, in the biome "crop" json setting. It is named "snowStackNatural_maxDepth"

**Comment by jredfox** [comment]
Could you point out where or is this the unreleased alpha?
http://i.imgur.com/cY10ZxP.png

**Comment by TheWeatherPony** [comment]
../BiomeSettings/settings.json
'..' means 'up one layer'

and it is released.

**Comment by jredfox** [comment]
Is this in a newer version for 1.7.10 ?It's not in my biome settings.json?
