### ISSUE TITLE
Request: Configurable Spring blocks 1.7.10 .json

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#104]
Version: [1.7.10]TheSeasonsMod-pre-3.0beta13d5 
Related enhancements that would work great with this: #51 , #55

I don't see any config options via .json to add any blocks with metadata support popping up in spring. If it wouldn't hurt too much Also support tile entities and nbt if the block contains an nbt. I don't know what I would use it for yet but, it would be nice to have.

I am asking for this feature since it's only editable in nbt data.

**Comment by TheWeatherPony** [comment]
pre-3.0 is no longer being developed, nor being supported.
pre-3.0 had this setting in NBT, just like all other worldly settings.
3.0-alpha does not yet have this, as this is the feature that will advance the version to 3.0-beta.
