### ISSUE TITLE
Request: Seasons Amount of Days Configurable 1.7.10

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#105]
Seasons mod although it supports custom per world changes via nbt has no main config to initialize default values for seasons days per season. 

I would also like to request per world .json files. It will generate this for every world in your saves folder. **you should be able to disable a season by setting the amount of days to 0. (Ice age config).** I was thinking having these .json's generate in the .json folder in it's on file and have the deafult ones in the main config or another file(separate from the .json).

#Seasons World .json file
"New World"{
"spring":10
"summer":0
"autumn":5
"winter":100
}

Seasons.cfg or maybe a separate file

#Default Amount of days per season
I:"spring":10
I:"summer":10
I:"autumn":10
I:"winter":10

**Comment by TheWeatherPony** [comment]
Both pre-3.0 AND 3.0 has the ability to change default settings before starting a world. That's the whole point of an editable default settings file. (Technically, 3.0 has TWO default settings files, where the first one is the internal defaults used internally by the mod to be used as reference in all others).

3.0-alpha ALREADY HAS worldly json configs on a per-dimension basis.

Setting the length of a season to 0 already skips that specific season, and has been the convention of the mod for years. Likewise, setting the length to -1 makes it infinite.

Again, the mod already has it's worldly setting separate from the main config (hence the very name "WORLDLY settings"), and as the logic dictates, these worldly settings are stored with the world (dimension).
