### ISSUE TITLE
Seasons Still Setting day after Creation Of World 1.7.10

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#107]
Version:[1.7.10]TheSeasonsMod-pre-3.0beta13d5 
Images: http://imgur.com/p9YDOw1

Seasons Still Setting day after Creation Of World 1.7.10. within one minuet the seasons day changes after the creation of the world after you said you fixed it with the mod. I don't know about your 1.8.9 but, it's not working in 1.7.10.

**Comment by TheWeatherPony** [comment]
If you update the mod from [1.7.10]TheSeasonsMod-pre-3.0beta13d5 to [1.7.10]TheSeasonsMod-pre-3.0beta13d5, of course you're going to have that problem. The latest version is [1.7.10]TheSeasonsMod-3.0-alpha2. New version's changes are not retroactive to older versions.
