### ISSUE TITLE
Seasons Loading Twice If Put In Mod Folder

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#108]
Version: PML:10.3, Seasons: [1.7.10]TheSeasonsMod-pre-3.0beta13d5 (1)
Images: http://imgur.com/wuVjxWn

Seasons Loading Twice If Put In .minecraft/mods Folder. This needs fixing A: because, your instaltion video says it should work, B: it prevents players from playing because forge stops loading.

**Comment by TheWeatherPony** [comment]
Don't include the mod twice. Forge is correct in it's accusations.
