### ISSUE TITLE
Special Request: 1.6.4

### ISSUE THREAD

**Issue by GoafteIt** [TheWeatherPony/TheSeasonsMod#109]
I've seen mods listed for The seasons 1.6.4 but a lot of links have been junk. I've been building a city map for 3 years by myself and really want to see this aesthetic work involved in my map. I am willing to pay if interested?

**Comment by jredfox** [comment]
would you want a 1.6.4 backport with bugs or wait and then ask again? There are configuration needs, Non user friendly nbtedits, and some minor/major bugs

**Comment by GoafteIt** [comment]
I don't mind most bugs. I'm just looking for a backport of the seasons mod
since I can't really update my saved city.

**Comment by TheWeatherPony** [comment]
I still have the mod's ancient 1.6.4 builds on my Dropbox, if that would be satisfactory. They aren't as compatible as the 1.7+ builds though, sadly. If so, would you mind dropping me a line on the forums? They functionally replace (and so the distribution files contain) whole modified class files, which is no longer acceptable.

**Comment by GoafteIt** [comment]
black.bravo.charlie@gmail.com      thank you!

**Comment by TheWeatherPony** [comment]
Not quite where I meant, but alright...

**Comment by GoafteIt** [comment]
Ah, then what did you mean. And this forum?

**Comment by TheWeatherPony** [comment]
I was meaning the forum the mod uses, minecraftforum.net, via private message.
Though the email you gave above works, I guess. Deleted it for you the moment I saw it...
