### ISSUE TITLE
 Exception in server tick loop beta8b

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#11]
http://pastebin.com/KmyxNteX

**Comment by jredfox** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAA? I can't paste more then 10 pastebins in 24 hours without an account so there is a limit on the amount of work I can do.  Now I can only do 25 per 24 hours .

**Comment by TheWeatherPony** [comment]
Duplicate of #8
