### ISSUE TITLE
Fix Vanilla Snow Logic

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#112]
Version: mc1.7.10-?

Quote by you:
"Related issue fixed - a missing ! (not symbol) in part of the snow code. Problem stems from rain and snow being the same thing in some areas, but not the same thing in others. May fix #64, but also may not.
Leaving open as a feature request"

Have you tried forge byte code manipulation or possibly using your pml tool to fix this?

**Comment by TheWeatherPony** [comment]
"Related issue **_fixed_** - a missing ! (not symbol) in part of the snow code. Problem stems from rain and snow being the same thing in some areas, but not the same thing in others. May fix #64, but also may not.
Leaving open as a feature request"

**Comment by jredfox** [comment]
good pm me a response via mc forums. I sent you a list of bugs that have to be fixed for seasons to become stable enough for modpacks regular modpacks at least
