### ISSUE TITLE
server tick loop  java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#14]
this is slightly different from the other server tick loop but, the crash report reads different. do not instantly amuse that this is a duplicate bug. read both of them these are different. 
http://pastebin.com/KYZma2c8

**Comment by PitchBright** [comment]
What were you doing at the time this crash occurred? Loading? Playing?

**Comment by jredfox** [comment]
loading a world and adding mods that I had to take out. I don't know which ones

**Comment by TheWeatherPony** [comment]
While it may appear different, it has the same cause and fix as #8.
