### ISSUE TITLE
Already tesselating!

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#16]
Already tesselating!
version: beta8b and beta8c3 ? 
http://pastebin.com/MAtgT4pX

**Comment by PitchBright** [comment]
Stacktrace says it's not a Seasons bug. Please close.

**Comment by TheWeatherPony** [comment]
Duplicate of https://github.com/TheWeatherPony/ProjectPrivateRainbow/issues/13
