### ISSUE TITLE
Seasons Cold Weather Bug

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#18]
version: beta8c3
This occurs if a biome already is cold and it tries to snow. what happens is it doesn't show the snowing animation but, places snow blocks please fix this. The spring rain bug pitchbright already reported that to you and you said that was fixed.

**Comment by TheWeatherPony** [comment]
#1 is a totally different issue - that problem is about temperature, and is a bug from vanilla.

**Comment by jredfox** [comment]
yeh but still buggy

**Comment by TheWeatherPony** [comment]
That's why I didn't close it. I'll need more information to speed up my search for a cause, but I'll request it as there's time.

**Comment by TheWeatherPony** [comment]
Question: when it doesn't show the snowing animation, is it showing the raining animation instead, exactly like in PitchBright's issue?

**Comment by jredfox** [comment]
no it's showing no animation.

**Comment by jredfox** [comment]
Issue appears to be fixed in the latest version.

**Comment by jredfox** [comment]
Closed

**Comment by jredfox** [comment]
I will re-open this issue or the spring rain bug if I encounter any bugs when I test seasons in every season again soon.

**Comment by TheWeatherPony** [comment]
If the bug for this issue is found again, please do reopen this. :)
The rain/snow bug (where one is rendered, but the other takes effect) is a vanilla bug, which should now be fully avoided, based on how temperatures are now calculated.

**Comment by jredfox** [comment]
ok thanks.
