### ISSUE TITLE
PML Crop Edits exception ticking world

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#20]
Ok so in lator versions of the launcher the teeselating errors have been fixed but, my fan runs constantly to keep up. This error with orespawn. also the incompatibility fixed as the launcher fixed but, is highly extremly laggy with orespawn now and here is the original crash. 
fixed beta8c3 only on the updated launcher 
not fixed older launcher on beta8b
http://www.mediafire.com/view/9d82714b79yddc9/OrespawnIncompatibility.txt
the question is is this fixed?
java.lang.NullPointerException: Exception ticking world
    at weatherpony.seasons.pml.edits.block.BlockCropsEdits.getCropInfo(BlockCropsEdits.java:33)
http://www.mediafire.com/view/kek5y91u5dgrecz/pml_block_edits_ticking_world.txt

sorry for this being realy messy to lazy and I ran out of time to fix this

**Comment by TheWeatherPony** [comment]
Crop code has already been fixed and improved for future versions, including performance-wise.

**Comment by jredfox** [comment]
Nice wanted to make sure.
