### ISSUE TITLE
Realy Weird Crash

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#21]
Minecraft crashed but, didn't generate a report
http://www.mediafire.com/view/lfkt7710mtx50qh/Realy_weird_crash_report.txt

version: beta8b or beta8c3 I forget

**Comment by TheWeatherPony** [comment]
This is a crash from within the Java Virtual Machine. I will make sure that the natives I use are up to date as needed. This is the only thing I can do about it. If the natives are current, then it is not a problem with anything I am doing. I will close this if and when I am sure I have exhausted everything I can do to resolve it.

**Comment by jredfox** [comment]
I see no further issues with this I think pml has been fixed. I havn't had this happen since like beta8b
