### ISSUE TITLE
[Closed Fixed Issue] Ticking memory conection when tabbing

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#23]
Status: fixed beta8b
Reason Marked: documentation 
What use to happen: if you pressed tab with /seasons set seasons (tab) it would crash
Crash Report
http://www.mediafire.com/view/1ekye3rkbmtp532/%238_when_pressed_tab.txt

**Comment by jredfox** [comment]
How do you close an issue or can only the owner can do that?

**Comment by TheWeatherPony** [comment]
Already fixed.

**Comment by jredfox** [comment]
yeh I know That's why I saidn [closed Fixed Bug] I reported this for documentation same as the other thread that said the same thing.
