### ISSUE TITLE
Unable To Recreate A world Due To It Hanging On the End Or End Biome (9)

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#25]
Recreating world works on a prior release bet8c3 however it doesn't work on beta8c4
Here is the server console http://pastebin.com/akht6NYV
Version: beta8c4

Steps Taken:
1. deleted all the saves 
2. created a world and recreated it
3. failed to recreate world it sat on converting world
4. crashed minecraft
5. deleted seasons.dat and crops .dat in the first world
6 recreated that the first world with the seasons.dat and crops.dat then it failed
7. the console read this at the end and sat there at loading dimension 1 (the end)
 [Server thread/INFO]: Total conversion count is 0
[Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[Server thread/INFO] [FML]: Applying holder lookups
[Server thread/INFO] [FML]: Holder lookups applied
 [Server thread/INFO] [FML]: Loading dimension 0 (Copy of New World) (net.minecraft.server.integrated.IntegratedServer@2f3623ef)
[16:45:24] [Server thread/INFO] [FML]: Loading dimension 1 (Copy of New World) (net.minecraft.server.integrated.IntegratedServer@2f3623ef)

Additional Notes:
8. it isn't releated to hot or cold biomes lists. I tried to recreate a world with empty cold and hot biome lists and it still hangs on dimension 1. It worked when creating a normal world.
1.  tested prior version it recreated the world successfully deleted all of pml seasons mod pml dev then updated it for further testing.

Further testing in super flat world creation:
1. Might not possibly be The end dimension. Instead might be the biome (sky:id:9) because, I set the biome id to 9 on presets on the super flat. and that didn't work.
1. tried it with just pml (without TSM) and it worked creating an end biome in the overworld
2. reset appdata tried to load the end biome with seasons in the overworld then it worked
3. tried the same thing for recreating it but, it gave the same errors I don't know what this means~~
4. after creating end biome in the flat world It didn't want to create the default world. 
5. after creating several worlds I tried to create the end biome in the flat world again and this time it didn't work.

**Comment by jredfox** [comment]
why is github editor glitching my work out every time first it was 6 then 66 now it's back to being 4 last lines

**Comment by PitchBright** [comment]
Because I'm editing your notes for accuracy.

**Comment by jredfox** [comment]
I reset my appdata and it worked loading the end biome I don't know why it wasn't working before. as for it hanging on the end dimension that is probably why It couldn't recreate the world

**Comment by PitchBright** [comment]
What do you mean you "reset my appdata"?

**Comment by jredfox** [comment]
deleted everything and got a fresh version of forge ran it then installed pml and the seasons mod

**Comment by PitchBright** [comment]
Okay. I understand. What you mean was, you did a clean/fresh install of minecraft, forge, PML & TSM.

**Comment by PitchBright** [comment]
Question. What do you mean by no.4:
"4. after creating end biome in the flatworld It didn't want to create the default world."

**Comment by PitchBright** [comment]
Do you mean:

"I tried to create a Sky biome based Superflat World, but it failed."

?

**Comment by jredfox** [comment]
it hung at loading the end dimension again when I went back to creating the world but, this time it wasn't recreating the world.

**Comment by PitchBright** [comment]
Okay, that's weird.

Does that mean you were able to successfully create a Sky biome-based superflat world then?

**Comment by jredfox** [comment]
it won't let me edit the forum. after so many worlds created it won't create an end biome in the superflat presets. Edit: working now

**Comment by PitchBright** [comment]
Our tests showed that it never was able to create the Sky biome in the superflat world.

**Comment by jredfox** [comment]
our tests were inaccurate because, we had several worlds and or some corruptions. This is a really weird complex bug I am further testing this out.

**Comment by PitchBright** [comment]
That doesn't make sense. Corruptions? Several worlds? You cleared your saves folder of saved worlds each time. Check your skype.

**Comment by PitchBright** [comment]
Closing this issue… to create a new report with new findings.

**Comment by PitchBright** [comment]
_This text will be italic_

**This text will be bold**

`This is code`
