### ISSUE TITLE
Unable To Create 2 Worlds Without Restarting Mc

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#26]
Version: _beta8c4_
Successful world http://pastebin.com/U98h2RYz
Unsuccessful world: http://pastebin.com/akht6NYV

I am unable to create a 2 worlds no matter what without restarting mc. It works after you restart mc and it creates a world.  Here are the steps I took to come to this bug. It seemed to get stuck at the end dimension because, that is the last thing it loads.  However I took the time to create a successful world and the next line was at the crop manager.

Failed Attempt 
1. started mc with pml/seasons
2. created world then I saved and exited the world
3. created the second world and got stuck at converting world. The console said it got stuck at loading the end dimension 1 and didn't load anything else
4. closed minecraft with task manager

**Successful Attempt**
1. created world saved and closed it
2. quit minecraft and relaunched
3. created a second world 

Conclusion:
Two minecraft worlds cannot be created in a single minecraft launch.  This needs to be fixed because, plenty of people will want to create more then one minecraft world on a single launch for many reasons. I found that there are two possibilities that would cause it.  

First Cause Conclusion: Stopped at loading the dimension of the end. **[Line 198]**
[Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@4d4cd14f)

Second Conclusion: loaded crop manager from the next line after the failure  of the last  successfully created world. **[Line 199]**
[21:40:54] [Server thread/INFO] [STDERR]: [weatherpony.seasons.world.crop.CropManagerBase:load:344]: Seasons starting crop setting load code

**Comment by jredfox** [comment]
'Testing'

**Comment by TheWeatherPony** [comment]
Fixed the inability to load a game after leaving a game, for the next version.
Logs/reports did not assist for this issue, but I found and fixed the problem anyways.

The end's crop settings started loading on line 214 of your log, and finished loading on line 222.

**Comment by jredfox** [comment]
ok that's great. I also noticed in the version I launched mc created a world , then quit and saved it . After that I deleted dimension 1 folder in the world and recreated a world and that worked on a single launch. so it has something to do with the end but, could possibly be the crops to. hopefully this is totally 100% fixed though
