### ISSUE TITLE
Birch Leaves Nearly Remain Unchanged All Year

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#28]
version: beta8c4
Priority: Low
Image: http://imgur.com/a/jdsbW _plese ignore the last image_
Birch trees remain unchanged untill fall or not noticible change untill fall and maby a very small difference in change in winter.

**Comment by TheWeatherPony** [comment]
This, and all other plant coloring requests, will be "fixed" when the upcoming coloring overhaul is finished.

**Comment by TheWeatherPony** [comment]
Plant coloring has been overhauled so that resource pack makers have control over these things, starting in the upcoming "pre-3.0 beta13"

**Comment by jredfox** [comment]
thanks glad to see your back modding.

**Comment by TheWeatherPony** [comment]
I never stopped... I just got buried by over-ambition throughout too many solo projects.

**Comment by VirtualGaming1** [comment]
how many projects do you have???

**Comment by TheWeatherPony** [comment]
I am the sole developer of PML, this mod (The Seasons Mod), Mo' Villages, Fence Overhaul, and a couple that I've forgotten. I also make a handful of mods for private servers and tinker with code towards making several more mods. I then have some projects outside of Minecraft and what I use for my MC mods.
