### ISSUE TITLE
[Enhancement] Fix Jungle Foliage Turns Frosty In The Winter 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#29]
Version: beta8b , beta8c3 , beta8c4
Image: http://i.imgur.com/glaItVj.png
1. Blacklist jungle leaves in hot biomes so they don't look like they are frozen in winter
2. Blacklist oak leaves in the Jungle/hotbiomes in winter.
3. Blacklist grass , grass blocks  from any jungle/hotbiomes in winter.

**Comment by PitchBright** [comment]
There is a Settings.cfg in the Seasons config folder that will keep Jungle leaves green all year round… that fixes your first one there.

I'm in favour of the second and third suggestions.

**Comment by jredfox** [comment]
I don't see an option in the settings.cfg for year round green on jungle leaves.  I see I could make it atumn in any seasons though.  here is my settings.cfg  http://pastebin.com/frERHDDw

**Comment by PitchBright** [comment]
"Autumn" leaves are the brown versions. If you want year-round green leaves in Jungle, set 'em to false, in each season.

Setting a leaves-type to true, in a specific season, tells the mod that you want the brown version of that leaves-type, in that season.

**Comment by jredfox** [comment]
it is false and the leaves are green all year. I was talking about jungle leaves being affected in winter by turning winter green like jungle leaves, oak leaves, and vines to. It does this in all types of jungle biomes. also the jungle leaves do this in the mesa biome meaning that it does this in all hot biomes.  the vines don't turn winter green in the mesa biomes.

**Comment by PitchBright** [comment]
I have no idea what you are trying to say. Your previous message said that you do not see a way to make jungle leaves, green, in all four seasons. I told you the solution was to not set them to turn brown (autumn style) by setting them to "true", and to set them to "false instead". 

You didn't say anything about "winter green" or mesa biomes... So I'm pretty sure that is not what you were talking about.

Just describe the problem, as clearly, completely and concisely as possible... the first time. Now then, what exactly is the problem?

**Comment by jredfox** [comment]
I can just show a video.

**Comment by jredfox** [comment]
Here is what I was trying to say: https://www.youtube.com/watch?v=UJSxIps60R4  also sorry for the default ezvid music you can mute it if you want.

**Comment by PitchBright** [comment]
Okay I understand what you're trying to say now. First of all, you need to understand how colormaps and biomes works. It's not like Pony is doing texture work in GIMP or Photoshop, and trying to make things look more-green or more-frosty. 

One of the things that's great about minecraft is, if you don't like how a texture looks, you can just change it yourself, with resourcepacks. You can change the minecraft colormap by adding your preferred colormap to a resourcepack.

http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/resource-pack-help/2234870-post-1-7-2-colormap-help

If I understand how TSM works, it's my understanding that a change in the temperature is what shifts the colormap towards or away from certain mappings for certain biomes. That means, when temperatures become configurable via JSON, you'll be able to make your jungle temperature the same value all year round, and then side effect is that the colours will be the same all year round.

**Comment by TheWeatherPony** [comment]
Pitch is correct for how temperature changes the colors. All that the mod does is overhaul how the color map file system works, by letting there me more color maps at once (the mod then switches which one(s) should be used among a slightly larger selection (two more maps)). This is also how the mod is compatible with texture/resource packs without being one.

Swamps are immune to the current seasonal texturing because the code for swamp coloring covers up (hides and replaces) the seasonal coloring code that is injected into the base-biome code. This is exact same reason behind why some mod-added biomes do not experience seasonal colors.

**Comment by jredfox** [comment]
well could you just do the jungles like you did the swamps?

**Comment by TheWeatherPony** [comment]
I didn't do the swamps - swamps are vanilla. I did no code to make swamps stay vanilla - vanilla made swamps stay vanilla.

**Comment by jredfox** [comment]
ok I will put another request.  I don't want jungles banned from seasons because, they have what's called a dry season in which for a period in time the leaves and vines start dying and turning brown.  I am not sure about jungle leaves.  maby you could just find a way to only add in fall textures for for that one season only?

**Comment by PitchBright** [comment]
The stuff is customizabe. If you want the leaves brown, set them to true. If you don't, then don't. If you want a particular shade of green, make your own colormap, it's that simple. If you had a better understanding of how minecraft works, we wouldn't spend so much time talking in circles, and explaining things over and over again.

**Comment by TheWeatherPony** [comment]
What you are after will be easier to do from the user side after the upcoming coloring overhaul is finished. It will also be easier after the upcoming customizable temperature feature is ready.
Because of that, this is very similar to #28

**Comment by jredfox** [comment]
nice to know I was just thinking it wouldn't just be jungles affected any biomes classified not as hot biomes but, not as cold biomes along with savannah biomes, jungles and any modded biome having that biome.
