### ISSUE TITLE
Failure to run on server (8c4)

### ISSUE THREAD

**Issue by TheWeatherPony** [TheWeatherPony/TheSeasonsMod#3]
Servers are unable to start with 8c4 due to a ClassCastException: com.google.gson.stream.JsonWriter cannot be cast to com.google.gson.stream.JsonWriter

Version: beta8c4

(making an issue for my own code for demonstration purposes)

**Comment by TheWeatherPony** [comment]
Fixed for the next version. Servers will successfully start up, unless something else goes wrong.

**Comment by jredfox** [comment]
It worked on beta8c3 for me

**Comment by TheWeatherPony** [comment]
This was an issue specific to 8c4, and was not present in previous builds.

**Comment by jredfox** [comment]
ok reporting bugs will put the versions after I do them but, they are all beta8c3 and beta8b I have had those crashes on both mostly.
