### ISSUE TITLE
Leaf Textures Are Off As An Item From What Season It is in

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#31]
Version: beta8b,beta8c3,beta8c4
Priority: Low
Images:http://imgur.com/lxPd8nS 
Images: Secondary explination http://imgur.com/a/vVIK5

The textures as an item and they are not the same as the blocks of the leaves during whatever season it is. I suggest adding this as a solution; Make it like you did for flowers so that it will change to whatever season it is in.

You don't have to change it per biome since that is complex in for and item and might lead to bugs. So I suggest to fix this and get the default seasons texture.

**Comment by TheWeatherPony** [comment]
I'll make a poll for that at some point, since it does make the blocks more difficult to identify quickly by sight.

**Comment by VirtualGaming1** [comment]
I know a Mod that will help you to figure out what leaf block it is and its called Waila. If you want me to get you a link of the mod let me know.

**Comment by jredfox** [comment]
did you even read what I said? do you even read? the leaf textures are off from what season it is in your inventory. for example oak leaves are green in your inventory and brown when you place them down, and green in winter then you place them down and then they are frosty.

**Comment by TheWeatherPony** [comment]
For many cases, this has been fixed for the upcoming pre-3.0 beta13. Resource pack makers can control many of them via the "biomelessColor" component. Only items that use the block model are applicable to this new feature. This also resolves the request without the need for a poll.

**Comment by jredfox** [comment]
wait I was talking about in your inventory does it color them in your inventory?

**Comment by TheWeatherPony** [comment]
If the item form is rendered as a block, and the block supports the new coloring, then the item form will usually support it. 👍

**Comment by jredfox** [comment]
well do you detect this coloring on block properties foliage or an array list which you defined. If it's an array list you need to setup an xml list so people can add their own leaves / foliage .  If you take a look at zzzzz custom configs It has great xml format simple to use and easy to learn. I think when you start adding more config options you should do booleans and if and array list xml format.  Also bad mobs does this xml thing to.   It can be easily edited with notepad.

**Comment by TheWeatherPony** [comment]
I detect what blocks support the settings by... keeping track of which ones ask for settings.
The configuration uses .xls format (a spreadsheet format), which can easily be edited with Microsoft Office or free open source alternatives like Open Office. I will never make xml a primary configuration format for anything I make, as merely looking at xml or xml-derived text gives me migraines. I do not see how there could be any more configuration options for this at this point. The configuration already uses a boolean setting, and an array would be outright worthless in this. This configuration content is not for users to work with, but rather for resource pack makers (and users wishing to make a custom resource pack to customize their experience).
