### ISSUE TITLE
Snows In Beaches And River Biomes In Or connected To A Hot Biome

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#32]
Version:beta8b,beta8a,beta8c3,beta8c4
Priority: Medium
Images: http://imgur.com/a/uJfs4

It snows in winter at beaches and river biomes connected to or in a hot biome.
I suggest you fix this by 1.0 release of seasons but, for now it's not really a bug so you can ignore it right now.  

Possible Solutions: 
A: Add a hot beach and a hot river biome
B: make something super smart and clever without making a new biome to replace the default rivers and beaches.
C: Come up with something

**Comment by PitchBright** [comment]
Nothing can be done here, short of creating and adding new sub-biomes to each biome-type for the off-chance that they have a beach generated beside them. Seasons mod isn't into adding new biomes. If you can find a mod that adds new sub-types of beaches, then you can configure Seasons to handle the temperature accordingly.
