### ISSUE TITLE
[Suggestion] Operation Spring Green

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#33]
Version: beta8c4,beta8c3
Priority: Low
Images: http://imgur.com/iuYwEqW
I don't like the newer green textures in the spring. Make it so it's more like spring green please. Or at least make it look nice. For the fun of it make an option in the config to look like alpha in spring? Don't worry about this though worry about your mod because, all these "Low" priorities don't matter too much.

**Comment by TheWeatherPony** [comment]
This, and all other plant coloring requests, will be "fixed" when the upcoming coloring overhaul is finished.
Combining with #28
