### ISSUE TITLE
[Bug] The Stripe Lands 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#37]
Version: beta8b,beta8c3,beta8c4
Priority: high
Images: http://imgur.com/a/un6mt
Ocean Version: http://imgur.com/a/EHcOv

during the winter in many biomes there is a random snow generation without and incident of it having snowed yet and only generates snow stripes everywhere randomly. It seems to go endlessly to infinity in two directions like that of a line.

Similar Issues:
there is a similar issue with it generating snow and creating snow less  boxed areas. There is also another issue of snow generating one sheet and if there is water it will turn it into ice. All of this occurred before snowfall happened in unloaded chunks.

**Comment by PitchBright** [comment]
Mojang bug. https://bugs.mojang.com/browse/MC-15820

Interrupted new chunk generation during biome decoration.
