### ISSUE TITLE
Seasons Generates One Sheet of Snow Randomly (Not Working Properly In Winter)

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#38]
Version: beta8b,beta8c3,beta8c4
Priority: High
Images: Sheets http://imgur.com/a/y6HdU
Images: Boxed Off: http://imgur.com/a/7wBhk

The world generates 1 sheet of snow every so often and generates it regardless weather or not it has snowed yet. It happens in alot of biomes that are not cold biomes (seasonsal biomes). It doesn't realy place them in all unloaded chunks during winter only half heartedly. It occurs in unloaded chunks. It occurs in all the ocean biomes and it generates 1 block of ice and 1 sheet of snow for miles. If there is water underneath it generates ice. It may or may not be cut off by another bug which cuts out snow generation. If you need further testing on this like xyz coordinates estimates I can do that. Sometimes this occurs if the ocean is big enough and it might look like an ice plains biome covered in 1 sheet of snow.

There is another feature not working properly. When it tries to generate snow blocks it tries to simulate and it fails ,gets replaced with air blocks or doesn't generate properly. Then there is no snow simulation at all. 

Might be Related To:
stripe lands https://github.com/TheWeatherPony/ProjectPrivateRainbow/issues/37
boxed off snow bug

**Comment by PitchBright** [comment]
Snow is automatically placed in biomes that should have snow in the Winter, if you are entering a new area and creating chunk… during Winter.

**Comment by jredfox** [comment]
This happened in the forest biome. It happened in alot of biomes

**Comment by PitchBright** [comment]
It snows in the Forest in Winter, does it not?

**Comment by jredfox** [comment]
yeh but, it's placing the block before it has even snowed.

**Comment by PitchBright** [comment]
like I said:
Snow is automatically placed in biomes that should have snow in the Winter, if you are entering a new area and creating chunk… during Winter.

**Comment by jredfox** [comment]
doesn't properly work As I am going to file in the next report. This works half hartedly maby I should have specified further that this occurs randomly not in all unloaded chunks. 

Is that better. I knew the snow thing was attempt to simulate but, wouldn't be as good as my enhancement idea with integration with time stamps mod.

**Comment by PitchBright** [comment]
Unloaded chunks? Or Newly Generated chunks?

**Comment by jredfox** [comment]
unloaded newly generated chunks. Is there a difference? I didn't think there was. I guess I don't know that much about the minecraft source code either.

**Comment by PitchBright** [comment]
Okay… read what I said about it, again. You'll understand why I'm saying it's working correctly. I think you're not understanding why this isn't a bug, but in fact, is a really cool feature.

**Comment by jredfox** [comment]
well if he thinks it's not a bug then let him close it. I just didn't think that he wanted this randomly generating snow in every biome when it's not doing a solid sheet for the final release.

**Comment by jredfox** [comment]
ok I see the issue I didn't post here it not working properly just the randomly generating sheets sorry my bad.

**Comment by TheWeatherPony** [comment]
Having a single layer of snow tiles is an old feature of the mod that was inside the worldgen code, but which was removed for several versions due to no directly obvious way to include it. Due to other refactored code, it became easier to re-add the feature.
This is not a bug, but is an intended and beloved feature.
