### ISSUE TITLE
Feature Request: simpler multworld support for consoles

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#4]
I couldn't seem to do the /seasons set season (any season) command in the console only as an op on the server on my client side. Then i tried to copy and paste the exact thing to my client and it worked. In the server console it said null world when I tried to run the command from there.
http://pastebin.com/xC2vtsC8

Ok it only works if I fallow the super advanced example
/seasons set world dimension season 
doesn't work
/seasons set season spring
/seasons set world spring

version: beta8c3

**Comment by PitchBright** [comment]
Is this a one-time thing? Or can you recreate the issue?

**Comment by jredfox** [comment]
I think I could recreate this. Let me make a list to do

**Comment by jredfox** [comment]
Successfully recreated the bug. I controlled a then controlled x  them and put it in the server console and it said null world again.

**Comment by PitchBright** [comment]
What does "null" mean? What does "world" mean?

**Comment by jredfox** [comment]
nothing. the world

**Comment by jredfox** [comment]
java.lang.RuntimeException: null world
        at weatherpony.seasons.command.Set_season.processCommand(Set_season.java:184) ~[Set_season.class:?]
        at weatherpony.util.command.SubCommand_base.StartCommandProcess(SubCommand_base.java:55) ~[SubCommand_base.class:?]
        at weatherpony.util.command.SubCommand_Compound.processCommand(SubCommand_Compound.java:96) ~[SubCommand_Compound.class:?]
        at weatherpony.util.command.SubCommand_base.StartCommandProcess(SubCommand_base.java:55) ~[SubCommand_base.class:?]
        at weatherpony.util.command.CommandCompound.func_71515_b(CommandCompound.java:67) ~[CommandCompound.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by PitchBright** [comment]
Exactly. "Null world". "The world is missing". You forgot to specify the world's name when you entered it in the console.

**Comment by jredfox** [comment]
Do I seriously have to do a youtube video? I copied and pasted the exact command from the command that worked but, I first changed the season so I would know if it changed or not.  It worked in mc client it didn't work in mc console

**Comment by TheWeatherPony** [comment]
Added additional explanation logging. In essence, you must specify what world should be changed when performed from the console - there can be a very large number of worlds at any time, and the console is not in any specific one already, so one must be specified by both the single-word name and the dimension number. For servers, the world is usually called "world" and the overworld is dimension number 0.

Thus, the command should likely have been: /seasons set season world 0 name-of-season

**Comment by jredfox** [comment]
I never had to in client version nor even when on the server on my client side opped.  There is only one world on a server could you fix this on the console in future versions?

**Comment by TheWeatherPony** [comment]
When used by a client that is connect to either an integrated or dedicated server, the player is already within a world/dimension combo. The world and dimension can still be supplied, but default to the one the connected player is within.
On a vanilla server, there are THREE worlds - the overworld, the nether, and the end. While the nether and end do not exhibit the seasons in the same way, the logic is still there. Furthermore, mods are free to add an unlimited number of additional dimensions, and some even load additional overworlds. By requiring the world name and dimension number, the commands develop a form of multi-world support.

**Comment by jredfox** [comment]
still isn't working.

**Comment by jredfox** [comment]
can you simplify it for servers?

**Comment by jredfox** [comment]
Ok it only works if I fallow the super advanced example
/seasons set world dimension season 
doesn't work
/seasons set season spring
/seasons set world spring

**Comment by PitchBright** [comment]
Do I seriously need to make a YouTube video to show you how to enter a command into the console? It's not rocket science… or "super advanced".

**Comment by jredfox** [comment]
no it's just I never had to type the advanced command except for the server console I am asking to simplify it to /seasons set season spring 
semi advanced /seasons set world spring
and all the codes on the console works for the advanced
/seasons set world dimension season

**Comment by PitchBright** [comment]
You're not understanding something. The reason you need to specify the world and dimension via console is because the console can be running multiple worlds, with multiple dimensions. "Multiworld".

The reason you do NOT need to do it when you are in the game, is because you are PHYSICALLY standing in the world and the dimension that you want to affect the change.

**Comment by PitchBright** [comment]
You can close this issue @jredfox

**Comment by jredfox** [comment]
it's marked as an enhancement . it's sword of annoying to type the absolute value of the full advanced command that seems not user friendly to me.

**Comment by TheWeatherPony** [comment]
I believe I may possibly be able to simplify it by removing the requirement of specifying the world's NAME - I will need to do more research into other mods to confirm, especially multiworld mods/plugins.

The NUMBER will always be required, but is not as hard to work with as needing both.

**Comment by jredfox** [comment]
Thank you

**Comment by TheWeatherPony** [comment]
Starting in the new 3.0-alpha for 1.8.9 (which has been released as an Alpha):
/Seasons set season [{dim number}/{player name}] {season name}
/Seasons set day [{dim number}/{player name}] {day number}
