### ISSUE TITLE
Configgable Snow stack size by Season

### ISSUE THREAD

**Issue by PitchBright** [TheWeatherPony/TheSeasonsMod#40]
Configgable Snow stack size by Season via JSON or txt.cfg.

**Comment by jredfox** [comment]
I know users if it were public would be asking for it in the config setting if they just wanted one stack of snow like the way vanilla operates.  I also would like .json file to configure the height The_WeatherPony Could you do both?

**Comment by PitchBright** [comment]
I'm with @jredfox . JSON for snow stack size on a per-biome, per-season basis. (For example) That way the Tundra biome can have snow 10 layers deep in the Winter, and the Alps can have it 14 layers deep. As well as say 5 & 7 in Autumn or Spring, etc etc.

**Comment by jredfox** [comment]
ok so per biome configuration. for a basic configuration disabling snow from stacking would be a nice and simple option rather then going through the entire .json file.

**Comment by TheWeatherPony** [comment]
jredfox, there is a way to disable snow from stacking beyond one snow tile - set the snow setting "tilelayerM" to 1.

All NBT settings will be migrated over to json over time.

**Comment by jredfox** [comment]
talking about making a config option to just enable global snow tile height and or snow block height.  I think I should make a new forum for enhancement then for this. When I said global I ment every dimension seasons are in.

**Comment by TheWeatherPony** [comment]
When NBT settings get migrated over to json, they will use the same system as crops do right now. The crops already support the loading of composite settings, meaning other settings will as well.
In the meantime, all worldly settings are generated based on the worldly template file in the config folder.

**Comment by jredfox** [comment]
Yes but, I was saying could you add an option to globally configure the snow tile and block height of the snow? or am I going to have to configure .json in every single biome making the snow stack size to be 1?

**Comment by PitchBright** [comment]
He said "Yes, there is right now", and "Yes, there will be in the future".

**Comment by TheWeatherPony** [comment]
Added in the new 3.0-alpha for 1.8.9 (which has been released as an Alpha)

**Comment by jredfox** [comment]
I forget did you also add the ability per biome as well and does this override the biome or is it the other way around?

**Comment by PitchBright** [comment]
@jredfox It works the same way crops do.
