### ISSUE TITLE
Seasons Official Suggestion List For 1.0 Release

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#41]
Version: Release
Priority: optional
Download Text Document: http://www.mediafire.com/view/hduwwh35q0z2rop/SeasonsOfficialSuggestionList.txt

Official Seasons Suggestion List for 1.0 Release PLEASE POST YOUR SUGESTION LIST BELOW IN THE COMMENT SECTION. 

**Clarification of what I meant by "Config" is seasons.cfg . If I say suggestion to be in .json then I suggested it to be in a .json**.  Also the word you in this document refers to the creator of seasons (The_WeatherPony)

1
no option in config file with just notepad to change the 7 day season 4 seasons in a year to 365 days in 4 seasons

Add config to disable this and have it in a specific season and day every time.

---
# a

start out in either same season was last in or rotates seasons per world
# b

can start out in random day in a season upon creating world

---

2
no option in config to change the grass to winter dead brown. No option in the config to have the foliage brown however if it snows it has a chance to be frosty green like it does in real life but, it depends on your biome type (this would only effect seasonal biomes. It won't effect cold biome and of course won't effect hot biomes)

---

3
suggestion
make trees have no leaves and let them be all stickish except for jungle trees, spruce acacia and in hot biomes,
and also allow to add trees / leaves in the config file for twigs. for the hot biomes let them be brownish.

---

4
have an option in the config to add leaves to autumn 

---

5
after 1.0 let's add dynamic seasons  and have more then one texture per id 
as optional and you can add a whole bunch of crazy configurations. 

---

6
add elevation/lake participation affect of snow

---
# Feature

acia mountain biomes should have snow if in the mountains
acia biomes should rain twice a year

---

7
spring should be the first summer autumn then winter not 
/seasons set season (tab) autumn (tab) winter (tab) (new world)

---

8 
add a config option to add a biome to classify it as seasonal , hot , cold
or extreme hills , and desert type themes.  

---

9
doesn't start on season day 0 when doing a command to be a new season you have to
do /seasons set day rather then /seasons set season and it is day 0
also when creating a world.

---

10
/seasons set season fall isn't an option CONFIRMED

---

11
option to blacklist a dimension that seasons will affect/biome

---

12
sinking through snow option in config

---

13
See mod owner that raged quit to get started. He had it working just with a couple bugs
https://github.com/TheWeatherPony/ProjectPrivateRainbow/issues/36
Make Time stamps mod and season addon to fix many bugs. See suggestion of enhancement of Rendering seasons in unloaded chunks. 
Also when you implement this delete all biome decorations that have nothing to do with texturing rendering except for adding plants back growing in the spring

---

14
Have flowers grow grass and plants go back in the spring also make it so that it works with modded items by making the foliage of chunk generation to be the same as the modded biome intedted for foliage

---

15
option to enable winter snow during any season in any biome (also complete controll of seasons 
adding any season to replace the seasons configurable days and time the season is and make it biome specific/dimension specific)

---

16
dynamic seasons (snow roughly around 1 sheet at a time and simulates through time stamp and time stamp seasons addon SMOOTHER SNOW/ICE FORMATIONS)
have textures slowly become the ones from the next season

---

17
snow drifts

---

18
ice burg drifts(low priority)

---

19 
Have seasons argue back and forth with the weather untill it is the next season and in colder climates make summer shorter

---

20
Have ice crystals form , snow icicles and stuff to,
frozen rivers cool stuff

---

21
sapling support for fall

---

22
add multiple blocks of leaves color for one id of a block and make it in a regular config file not a json 
the leaves would be purple, yellow green, ornge,brown, black make highly configurable and can change on the day of a certion season

---

23
Make an option to add classic textures and biome foliage from early betas 

---

25
in the fall leaves blocks fall and you pick them up with a rake and get leaves. You can make leaves pile and they are flammable unless it rains which turns them into wet leaves. 
also make it so that there are every single color of leave blocks based on the tree it falls from.
Have fall leave blocks be the color of the leaves and same leaves from that tree. Have the leaves be = to snow stacking and leaf falling be similar to snow piling.
 Now the question is what about the tree? Should be a twig left should there be a branch should trees spawn with branches 
should there be nothing there then grows back in the spring.  
Leaves at any stack size can be picked up with a rake.  Have leaf block id's be 1 I'd for 1 type of leaf but add the: props for different colors.

---

26
in the config for some people who would want this add an option to only get maximum of 1 sheet of snow during winter

---

27
add snow shoes to keep you up from sinking in the snow if that option 
is enabled in the config make the properties similar to the snowfall mod.

---

28
add snow shovels and can break any snow block in any snow forum both with and without the snow falling on in the config.

---

30
option to disable dynamic seasons after you add it. this would be configurable in all forms
(texture dynamic , weather and also some other stuff)

---

31
fix incompatibility with the weather mod

---

32
Add sleds and skis. Possibly add snow boards

---

34
Make everything configurable. 

---

35 EASTER EGGS (Seasons)
Add some seasonal Easter eggs. Like on the 5th in winter day change Mc to Christmas textures in Mc default Christmas textures. At Halloween make pumpkins go on mobs heads. Add a config option not a Json to enable how many days a seasonal tear is and how long each season is.  
Do something special for thanksgiving. Even Canada has a thanksgiving I think. America does. Make the aether on Christmas to aether Christmas textures Easter eggs.  
Make Easter eggs configurable. When April fool's day either change the skin to a villager Steve or in the future alex

---

36
Add an option to make it snow everywhere on Christmas day regardless of what biome you are in. make it 1/3 chance to be a white Christmas world wide for the rest that's up to you.
Then make a chat in the box that says
 Merry Christmas
Also displays at the same time: 
Happy  Hanukkah
Happy Holidays
happy Kwanzaa
Configurable to turn any of these off or all of them off.

---

37
seasons message for each holiday but, make it from every single country (this is for way down the road for when you ask for translators)

---

38
Make envoromine  so that you can't freeze to death on Christmas

---

40
Add a hot river and a hot beach biome to replace the default ones. 

---

+41
when and if you add frostbite back to seasons keep it disabled by default  if it detects envoromine.  Also make sure that frostbite can be turned off in the config. 

---

+43
after and if you add the compatibility of the weather mod add in blizzards with snowing falling fast  down. 

---

+44
add snow dynamics for 3.1 (more types of snow/ice)

---

+45
add mixed participation dynamic snows from powder to snow ice solid to solid ice.

---

+46
have the option to add any config option to make like snow in any season or fall foliage in any biome also can be configured in a specified dimension. 

---

+47
add an option in the config to blacklist any biome / dimension from seasons

---

+48
have seasonal textures for the desert like flowers on cati and well that's just about it except maby some brief summer flowers?

---

+49
add an option to have seasons in a specified order or to randomize the chance of each season .
+50
add an option in the future to make your own season :)
+51
add a biome whitelist if enabled 
+52
add a biome / dimension blacklist
+53
make aura lights
+54
make rainbows
+55
make seasons addon/easter eggs

---

**Comment by PitchBright** [comment]
1) You can set your NBT data to the following seasons lengths to achieve a 365 day year with seasons.

Spring: 93 
Summer: 93 
Autumn: 90 
Winter: 89  

You can also generate your world, save and close. Open the NBT, and manually set the season and day.

Agreed that config file would be a great place for this.

**Comment by PitchBright** [comment]
2)  config/Seasons/Settings.cfg
    B:Winter_AutumnGrass=true

**Comment by jredfox** [comment]
lol no nbt please. this is a suggestion list for config no npt please

**Comment by PitchBright** [comment]
Oh, I thought you were saying there wasn't an option to do the things you wanted to do.

Pony plans on moving the settings to a config file already. It's all good.

**Comment by PitchBright** [comment]
7) It's in the order of Autumn, Spring, Summer, Winter… because that's alphabetical, and that is the way Tab-Autocompletion works.

**Comment by PitchBright** [comment]
23) You can do with a Resource Pack

**Comment by PitchBright** [comment]
24) You have to set that up in Enviromine (Not a TSM thing).

**Comment by PitchBright** [comment]
26) Done by NBT. Will be done by config in a future version (afaik).

**Comment by PitchBright** [comment]
29) is not 12?

**Comment by PitchBright** [comment]
33) TSM has nothing to do with the sky. You want to look into a Sky mod for that. Check out Stellar Sky.

**Comment by PitchBright** [comment]
36) I totally disagree with this one. Sorry.

**Comment by PitchBright** [comment]
38) and disagree with this one. If you want enviromine to do certain things, you need to configure enviromine to do those things. And if it doesn't, then you need to petition those devs for that stuff.

**Comment by PitchBright** [comment]
39) Again, these things are not seasonal features… therefore not TSM.

**Comment by PitchBright** [comment]
40) This mod is about Seasons… not biomes. Use a biome mod for that stuff, or ask a modder to make a mod that does what you want it to do for those types of ideas.

**Comment by jredfox** [comment]
ok I am taking a look at what you said.  then I will make a list of changes to the suggestion list.

**Comment by jredfox** [comment]
**Update Suggestion List Log Version 1.1 (Seasons Version 1.0)**
removed 24 report to envormine
removed 29 duplicate of 12
removed 33 (commits shooting stars talk to stellar people but,report to seasons eventually for increased chances of shooting stars and commits)

---

+41
when and if you (The_WeatherPony) add frostbite back to seasons keep it disabled by default  if it detects envoromine.  Also make sure that frostbite can be turned off in the config. 

---

-39
removed partially 39 (rainbows will be a seperate suggestion for of a mod itself along with other asthestics) (removed aura lights suggestion I found out it has to do with seasons but, only that it is because, the sun is weird in the arctic and during the summer it is day for 24 hours a day. So basically nothing that has to do with seasons.)

---

made classic beta textures suggestions to be enabled in the config (forgot to add that) suggestion rather then saying add classic early beta editions. 

---

**Comment by jredfox** [comment]
Your Concerns: PitchBright
2) I meant dead brown I don't want golden grass or orange or even yellow I want the grass dead brown in winter. I also want the foliage dead brown in winter. after it snows if it is decidious to stay dead brown ( seasonal leaves)
then after it snows it has a chance for all the grass to turn frosty green or some brown patches (if dynamic seasons is implemented)

23) I want a config option to look like the early betas as an option.

36) Fine Update Suggestion: Add an option to make seasons snow in whatever biome you are in on Christmas day

38) I had to report stuff on both sides first seasons then envoromine needs to get together to do this. Also I don't feel like anybody should freeze to death on Christmas day even in the seasons mod. 

40) I know this mod isn't about biomes but, it's to fix the weirdness with hot biomes in winter. mojang created the frozen rivers and cold beaches to fix their issues to.

**Comment by jredfox** [comment]
ok is 3.0 coming out or you just never wanted to do any of these features. it a long variant list so if you don't like some suggestions just keeping looking down.  thanks you don't have to take any of them.

**Comment by PitchBright** [comment]
It's a laundry list of things YOU want in TSM, most of which has nothing to do with TSM, some of which are asinine requests (no. 38 is a prime example, people freeze to death regardless of what day of the year it is man, what the hell are you thinking?)… and the rest of it is either repeated elsewhere in the same list, repeated elsewhere on the github, or completely and utterly painful to read and to try to understand. It's a lot easier to just close a topic, than to spend the time trying to work through a lot of what you're writing, either because it doesn't make sense (when you read it out loud), or it's just hard to read because you're not using punctuation. In other words "kill me now".
