### ISSUE TITLE
Some crop types may not be loading properly.

### ISSUE THREAD

**Issue by PitchBright** [TheWeatherPony/TheSeasonsMod#49]
Farmers noticed that Reed grows same rate as vanilla.

I started a SSP world… and tested to see it for myself.

My Reed settings: http://pastebin.com/R0yaTEJe
Screencap after 5-10 minutes (in Summer): http://imgur.com/xMKGewz
Screen cap of crop directories to show date modified (World started at: 6:18am): http://imgur.com/NL8PC1E

Snippet of possibly unrelated NPE's on test server that I started up at the same time: http://pastebin.com/yXgXbpit

**Comment by TheWeatherPony** [comment]
Double checking - all crop types now work correctly?

**Comment by PitchBright** [comment]
I believe so, yeah. As for Reeds, it took some time for me to see some change in Reeds, so I assumed it was very slow because of my settings. Recently, I began to think it wasn't working, so I tested it tonight, and noticed that I had the ReedGrowthAtMetadata set to 15, when I should of had it set to 1.

I think everything will work fine there now.
