### ISSUE TITLE
PML Logging Out Of Stream Java Error

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#53]
version: beta10
Link: http://pastebin.com/ZBk1nK8t

I launched minecraft with the argument then it errered and crashed. I am not sure if this is my computer java minecraft or your mod.  This is the third mod That had this kind of error within a month.  If its not yours close it and ignore it. only forge an seasons were installed

**Comment by PitchBright** [comment]
That's Forge's stupid anvil animation being derpy. You can disable it in splash.properties in your config folder, under "enabled=false".

**Comment by jredfox** [comment]
ok but, it only happens once just randomly does forge know about this?  it isn't just seasons it does this with it also did this with mine and blade battle gear 2 just randomly
