### ISSUE TITLE
Ice Not Melting In Hot Biomes

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#54]
Version: beta10
Images: http://imgur.com/a/fD4DE

Ice doesn't melt in the desert or any hot biomes.  I thought you fixed this so snow and ice would melt by temperature?  did you remove this to get rid of the spring rain bug in the extreme hills? If you fix this make sure that the spring rain bug is fixed when you fix all the ice/snow/snowblocks/packed ice melts in the desert. 
1.  placed ice, packed ice, snow tiles,snow block, checked season it said spring in the desert biome.
2.  I didn't think it had to be a specific season to melt the snow and I watched for a minuet noticing that non of the blocks were melting in the desert.
3. tried it in other hot biomes and that didn't matter.

**Comment by TheWeatherPony** [comment]
Could you please try deleting the old worldly settings and template settings, and have the code generate fresh versions?

**Comment by jredfox** [comment]
I had a brand new forge brand new seasons brand new minecraft and I even refreshed the installation twice.  Ice still didn't melt nor snow.  maby it's the forge version? I am on a newer forge of 1.7.10-1588 the new recommended version

**Comment by TheWeatherPony** [comment]
Then could you double-check that "meltAttempt" in the snow logic section is 1/3 in your world's settings? 1/3 is the new default, while it was previously 0.
Could you also please test using a significantly larger sample, such as by making it snow beforehand?

**Comment by jredfox** [comment]
I mean by default in a desert or hot biome it should melt pretty quick? I thought snow melted in deserts fast because, I thought hot biomes made it melt faster?  is this not implemented ? I will test a large mass of snow in a hot biome.

**Comment by jredfox** [comment]
ok it works but, in winter in the desert it takes like 4 times as long for the ice to melt.  Check the tempiture of the desert how much is it affected in the winter.  hot biomes don't get cold in the winter so I don't see how or why it would be melting 4 times slower.

**Comment by TheWeatherPony** [comment]
In real life, deserts are not necessarily hot - they are merely very dry.
In the mod, "hot biomes" and "cold biomes" are not mutually exclusive. Besides - those lists deal with legacy settings and player exposure logic, and do absolutely nothing to temperature: changing the lists is not a way to customize temperature, even remotely.

Currently, all biomes change temperature seasonally by multiplying their temperature by a pre-set seasonal multiplier. With this, hotter biomes experience larger temperature swings. When melting snow, there is a "meltAttempt" out of 1 probability each time snow gets ticked that the temperature-based melting logic will be run. If that logic does get run, there is a linearly-temperature based probability that a single tile in the stack will be removed, for the temperature range [.15,.9].
While the math may need tweaking to better adjust for stacking snow, the idea is that the snow will never instantaneously melt in too large of quantities.
