### ISSUE TITLE
NBT Decorations Lists are empty

### ISSUE THREAD

**Issue by PitchBright** [TheWeatherPony/TheSeasonsMod#57]
I went to check on the server after reading #52 & #55 … and it was indeed in the wrong season… and then I noticed that things didn't look right on the server. So I checked, and ALL of my NBT configs for seasonal biome decoration… Flower, Grass, Mushroom and Saplings lists, for Spring, Summer, Autumn and Winter… for all of the Vanilla biomes are totally gone from my Seasons.dat file!!

**Comment by TheWeatherPony** [comment]
Should be fixed for next version.

**Comment by jredfox** [comment]
So they were blank. I thought they just weren't configured yet.

**Comment by PitchBright** [comment]
They're not configured by default.

Mine were configured, but then got wiped.
