### ISSUE TITLE
Twlight Forest Issues Upon Going To The Twilight Zone

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#58]
Version: beta10
Crash Report: http://pastebin.com/tPqJpXE5

Twlight Forest Issues Upon Going To The Twilight Zone

**Comment by TheWeatherPony** [comment]
This particular issue is fixed for the next version, but I found another one that I'll try to work out with Twilight Forest's author.

**Comment by jredfox** [comment]
I don't see any more issues with the twilight forest then it is with any dimension mods which is that they might be laggier then normal
