### ISSUE TITLE
weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:80)

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#6]
I have encounterd this with many crash but, at the end everytime it is caused by weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:80) . For all of this bspkrsCore was present however some but, not all were in game crashes. some occured upon trying to launch such as older versions of agricraft

Here are the crash reports I have documented.
elemental caves
http://pastebin.com/NHNSaDGe

MFQM(more fun quicksand)
http://pastebin.com/vHmZ3xZR

bspkrsCore
http://pastebin.com/1d1S3G2A

agricraft crashed upon launch
http://pastebin.com/i6umxXCD

version: beta8c3 and beta8b

**Comment by TheWeatherPony** [comment]
weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:80) is the new start of the program. That is why it is named "ReplacementMainThread" - it replaces the normal Thread of logic, for technical reasons.

Problems with this in the stack trace may or may not be related to one another, and should not be grouped together directly because of this commonality.

**Comment by jredfox** [comment]
but, this is a major bug and bkrs core I think has something to do with it to

**Comment by TheWeatherPony** [comment]
Incompatibility with bkrs core may be real - but the crash involving bkrs core and this line showing up in the trace are not indicative of a relationship. I will look into bkrs core crashes, but bkrs core crashes are no more related to that common line than the fact that both are written in Java for the same program, and are running at the same time.

**Comment by jredfox** [comment]
Then I have no clue why the others happened and I talked to all the modders they are convinced it's not a bug and it's not theirs

**Comment by TheWeatherPony** [comment]
I shall look in to the others, too, then. But they are not directly related issues just because of a commonality at the very bottom of the stack trace - especially for a Thread that is host to so many things (essentially the entire game).

**Comment by jredfox** [comment]
Yeh most of the crashes are caused from mod incompatibilities

**Comment by jredfox** [comment]
thanks
