### ISSUE TITLE
Various incompatibilities due to faulty bytecode injection -- java.lang.VerifyError: Bad local variable type

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#61]
Version: Beta 12b
Hardcore Ender Expansion http://pastebin.com/AmeqyNAW
AbyssalCraft Crash: http://pastebin.com/WPNAHqfn
TheBetweenlands: http://pastebin.com/Th8hJYBZ

In the next beta of seasons the previously  perfectly compatible hardcore ender expansion pack  mod was working in previous beta editions but, since the update it has crashed within seconds upon launch.

**Comment by TheWeatherPony** [comment]
Also impacts other mods, such as is seen in #79.
Problem originates from the hook injector in PML, which modifies that section of bytecode.

**Comment by TheWeatherPony** [comment]
This has been fixed by the new PML 9.2 update.
If there are any mods not fixed by this update, please let me know in either this or a new issue report.

**Comment by jredfox** [comment]
thanks it was incompatible with 14 dimensions and 2 of them were popular like mystcraft.  did you take a look a the temperatures issues yet? you fixed the spring rain bug before by raising the temperature in the extreme hills biome during spring but, is it back. I know it's a vanilla issue but , you could raise the temperature again?
