### ISSUE TITLE
No Message In Chat Saying The Season Has Changed

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#62]
Version: beta10 , beta8b beta8a, beta9

When the seasons transitions no  message pops up saying the season has changed. Also when you fixed this I know some people might not like it so; add an option to disable it in the config.

**Comment by TheWeatherPony** [comment]
It doesn't come up in chat - it comes up as a rendered overlay that fades away. There is already a server-side setting to disable it ("SeasonTransition").

**Comment by jredfox** [comment]
I am confused on how you just worded it. Well I guess I didn't get what you were saying then on the forum that it hasn't showed a message.  well I was suggestion a message then

**Comment by PitchBright** [comment]
I think the transition overlay, isn't working Pony. TMPM had his SeasonTransition set to 1 by default, and it didn't show the Season Overlay when the season changed.
