### ISSUE TITLE
[Request] Seasons Blacklist/Whitelist Biomes

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#63]
Version: beta10

I am request a biome blacklist for biomes that seasons won't affect and a biome whitelist so seasons will only use what biomes you tell it to. This feature would go along nice if this and blacklisting dimensions for seasons if that would be implemented.  How I see it being set up in the main config is setting either black list or whitelist use to true then only using that method.

**Comment by jredfox** [comment]
I also think this enhancement would work good with dimension blacklist/white as well. least priority for another update do bugs first.

**Comment by TheWeatherPony** [comment]
Everything involved can be done through normal means at this point.
