### ISSUE TITLE
Snows In The End

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#64]
Version: beta10
Console Log: http://pastebin.com/FLYLr9wA
Images: http://imgur.com/uWwB38k
Video: https://www.youtube.com/watch?v=60qc7HOJD3Q

I am able to make it snow in the end dimension with the biome (sky id:9) with some steps.  If you just did /seasons set seasons winter it didn't work and /toggledownfall it also didn't work.  Here is what I did and you can also so the steps I did in the video.   I tried with and without optifine and the result was the same.  

1 created world
2. /seasons set seasons Autumn
3. created end port and went in
4. /seasons set seasons winter in the end
5 /toggledownfall and went to the overworld
6. changed the overworld season to winter /seasons set seasons winter and it started snowing
7.  went back to the end and nothing happened 
8.  /toggledownfall  in the end 
9.  /kill 
10. went back to the end and it was snowing.

**Comment by TheWeatherPony** [comment]
The only thing that the mod does is change the temperature so that it snows when it would otherwise rain. This is likely just an extension of a vanilla oddity involving rain in the end via the same commands (minus the seasonal ones).

**Comment by jredfox** [comment]
well couldn't you ban seasons from dimensions at least?

**Comment by PitchBright** [comment]
@jredfox you'll be able to change the temperature of The End (so that it rains the way want it to, instead of snowing).

**Comment by TheWeatherPony** [comment]
You can already ban seasons from dimensions, using the "NoSeason" worldly setting. The banning process is simply not automated for creating new worlds (new game saves).

To explain Pitch's comment, I believe I've finished all the code needed for customizing biome temperatures. It's still possible that there could be issues, but the server->client transfer of default settings seemed to go alright.
