### ISSUE TITLE
Optifine Texture SmartGrass Render Issues

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#65]
Version: beta10
Images:http://imgur.com/a/SohVN
Images no optitfine smart grass off options fast graphics on:http://imgur.com/mnc9FmJ

Without optifine smart grass renders in both fancy and fast graphics in Autumn .  With optifine it makes you have to have either fancy graphics on or fancy grass on for Autumn grass to look right. If you don't have fancy graphics or fancy grass enabled it seems to just render the fast graphics with just green instead of orange sides of the grass in Autumn.  I suggest enabling a texture in fast graphics whether or not that smart grass works or not. Or possibly just fix the texture rendering with optifine.  Optifine is a necessary mod for all modpacks without it no modpacks would be possible without a powerful computer render animations better then laptops.  For instance without optifine and the animations disabled my pc at 8g of ram doesn't load anything without the animations disabled. You click on anything and it not responds and doesn't come back.

**Comment by TheWeatherPony** [comment]
Optifine is not a holy grail - except as a punch line for modding jokes. It's really, really truly, that bad.

TSM has its own version of fancy grass, which Optifine may be overriding the changes from when it's installed - "smartGrass" in the client config (default setting is true/enabled). I'll try changing when the setting gets applied through Forge, but that's the best I can do without looking at Optifunny's code.

**Comment by jredfox** [comment]
ok thanks
