### ISSUE TITLE
Snow Places On Half Slabs And Stairs

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#67]
Version: beta10
Images: http://imgur.com/a/OQvue

In vanilla snow doesn't place snow tiles on half slabs and stairs when seasons did.  It also looks weird on a half slab but, I could understand if you want to keep it on a half slab. It places snow tiles on stair blocks.  Is this intended and if so could you possibly make it better for stairs at least?

**Comment by TheWeatherPony** [comment]
There's actually worldly settings in the mod to have it not place snow on slabs, stairs, ice, glass, tilled soil, etc., etc.
Snow in general is a partially-finished multi-section overhaul. The snow placement and removal has been overhauled, but the collision, rendering, and break-box sections have not been.

I'll be adding some more code to snow for upcoming changes, which will make the snow logically closer to where it is intended to be (resting on top of the slab/stair/etc. under it).

**Comment by jredfox** [comment]
ok
