### ISSUE TITLE
Snow/Rain Is Longer Then Vanilla

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#69]
Version:beta10
Images: http://imgur.com/a/YzDxS
Minecraft wiki quote"The average rainfall lasts .5–1 days, and there is a .5 to 7.5 day delay between rainstorms."   The time it took for it to stop snowing/raining for me was around 1.5 days give or take a few hours. I don't think it's randomized like vanilla at all. I tested both snow and rain and they both gave me about 1.5 days when it's suppose to be 0.5-1day 1day being the most it can be.  I am not sure if this is seasons days it's trying to count or what because, it even rained/snowed longer then a season day. It started raining /snowing on the creation of the world and went the next day and continued into the night.

**Comment by TheWeatherPony** [comment]
I double checked, and the only place where the mod does anything with rain, even indirectly, is when the season is Winter and the legacy setting "WinterSnow" is enabled (disabled by default) - in which case the mod acts as if it is constantly enabling rain through commands. (And the only time it does anything with storms is in Summer with SummerThunder enabled (which is the default) - where it does the same kind of thing with storms, if it's raining.)

I'm not sure how or why the rain lasted longer, but sleeping should fix it - when waking up, any active weather timers are reset in vanilla logic - though if another mod is changing the weather length, it could also change the weather reset.

**Comment by jredfox** [comment]
I could double check this for vanilla 1.7.10 maby it's an issue with the new launcher however I can guarantee that without sleeping it lasts 3x more of the vanilla minimal is your storms minimal setting. I don't know what this is caused by all I know is that according to the wiki the rain/snow storms are off. maby you could force stop it randomly from vanilla time and set the max to one day again just as vanilla had it set to let me double check this and I will get back to you.

**Comment by jredfox** [comment]
ok it seems as if vanilla rain/snow storms are default. the wiki must have been wrong or outdated.
