### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#7]
I have no idea why I got a crash. All i know is I added a mod and when it tried to create a world and it spawned me  in or near a snowy biome it crashed.
1
http://pastebin.com/Gg34DaKD
2
http://pastebin.com/18xjcxGe

**Comment by PitchBright** [comment]
"Added a mod"

That's very helpful. Would you mind being more specific?

**Comment by jredfox** [comment]
not sure do you want me to take like 14 hours to recreate my alpha test environment of dinosaur heavy modpack and try it again?

**Comment by TheWeatherPony** [comment]
It's possible I already fixed this. I would like to hold off on testing for this until after the next build is ready, just in case.

**Comment by jredfox** [comment]
Well the thing is I don't know what I did to create this crash :(

**Comment by TheWeatherPony** [comment]
I'm afraid I'm not going to try to fix it until after the next version is ready and if it's reported with that version, as I've already made several line-number-changing alterations, so will have more trouble trying to match up the code than it may be worth - especially if I've already fixed it.

I'm closing this, but will re-open it if the problem is rediscovered in the next version.

**Comment by jredfox** [comment]
well can you leave it open so you and  me don't forget this a lagitament bug?

**Comment by jredfox** [comment]
I will test for the future and recreate my alpha modpack environment till I make it get this crash. it occured when I added extended farming? the seed was 2 with extrabiomesxl and the biome I spawned in was a cold one it was either mountain tiaga from extrabiomesxl or the snowy biome. if It doesn't crash no matter what that means you fixed it

**Comment by jredfox** [comment]
why pastebin? Could I use mediafire.com it has the same properties for reading crash reports

**Comment by jredfox** [comment]
I cannot test this to close it because, of a new crash that is incompatible with the mods that it was compatible from the mods it was before in previous versions

**Comment by PitchBright** [comment]
Got a crash report?

**Comment by jredfox** [comment]
yes, I am trying to find out what mod. it seems to be twilight forest however it crashed in an rpg modpack to . it might seem to be bigger then just one mod so I am going to test this for a couple hours

**Comment by TheWeatherPony** [comment]
Twilight Forest is already confirmed to be incompatible with beta9, though was not reported on here. I'll be addressing that problem soon.

**Comment by jredfox** [comment]
Report is made. I am checking for other incompatible mods. Do you think you know why in a short description on why this is happening. Even if you fix this the problem might appear in other mods as well.

**Comment by jredfox** [comment]
cannot recreate the issue for beta9 closing this now
