### ISSUE TITLE
Winter And Seasons Needs Temperature Adjustment 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#71]
Version:beta10
Images Snow Not Melting Properly: http://imgur.com/a/yRsdc  
Images Temperature Issues: http://imgur.com/a/hUj5k

Seasons temperatures seems reasonable except for winter. Winter the desert type biomes get so cold that they don't even melt snow except for like 3 blocks per 9 minuets. Desert biomes are usually hot year round and that is how they intended it to be when notch made minecraft.  The thermometer goes from like 200% to like 36% and stuff does not want to melt at all.  Here are the current seasonal multipliers 

Seasonal Constant Multipliers
Spring: 0.751x
Summer: 1.101x normal temperature
Autumn: 0.726x 
Winter: 0.187x
Minecraft Wki
"0.15 for snow, 0.15 - 0.95 for rain, or greater than 1.0 for neither."

I did the math and it looks like that was the cause of the jungle turning frosty it also looks like that is why the snow is taking so long to melt even in hot biomes during winter.  I suggest adjusting the winter temperatures.  I took the nether biome id in a superflat world set it to winter; it turned frosty green and then didn't want to melt the snow.  

**Seasons Temperatures Images**
In the images the first link here is what you  are seeing;
 image 1 desert in winter is frosty green.  
image 2 took 6 minuets to melt 2 snow tiles during winter from the nether biome:Hell
Image 3 a screenshot of the nether biome winter temperature 37% to  summer of 250% the spring temperature is 150% I don't think that's right for winter from a nether biome.  
Image4 the nether biomes Autumn temperature of 145%
Image5: a forest thermometer in winter to compare with the jungle in the next screenshot
Image6: jungle's temperature of 18% in winter It is 71% in spring, 105% in summer, 69% in autumn
Image7: Jungle Temperatures of summer of 105%
Image8:  Nether biomes spring's temperature of 150% compared to winter previous of 37%

**Seasons Snow Melting Images**
Image1: Doesn't snow in spring after 10 minuets of the extreme hills biome
Image2:  During winter the jungle biome 9 minuets worth of snow melting and still only melted 2 snow tiles.  

Conclusion: I think winter above all needs the most tweaking and adjusting of all of the seasons.   mooshroom biomes not melting during winter, jungles barley melting during winter , 
Spring needs some adjustment obviously because, it has caused some issues with extreme hills not melting at all during spring. I think maby per biome temperature per season might also lead to this fix for this specific types of problems.

**Comment by TheWeatherPony** [comment]
Biome temperature configuration should be finished for the next version, as I told you earlier...

Additionally, biomes are marked as not having rain/snow separately from being assigned normal temperatures - while biome temperatures of 1.0 and above directly correlate to a biome not having rain/snow in vanilla, the correlation is not guaranteed for mod-added biomes.

**Comment by jredfox** [comment]
I was saying the melting process of the snow and winter of hot biomes the temperature was way too low for it to be a hot biome and didn't really melt the snow.  I was just reporting everything just encase you didn't fix everything I reported here.

**Comment by jredfox** [comment]
Also can you make it so that you can config the biome temperature of each and every biome in .json or .cfg per season?

**Comment by TheWeatherPony** [comment]
That's already been done, via the crop setting code. json.

**Comment by jredfox** [comment]
I don't seem to see custimizable temperature what config file is it in? I looked at the crops and experimental settings. I found custimizable crops but, I didn't see temperature.

**Comment by TheWeatherPony** [comment]
it's in the next build
