### ISSUE TITLE
Compact Ice and Snow Blocks Doesn't Melt

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#73]
Version: beta10
Image: http://imgur.com/SuggIjy

The compact ice block and the snow block doesn't melt no matter what season/temperature it is

**Comment by TheWeatherPony** [comment]
This is currently an intended feature so that snow/ice builds aren't completely destroyed when the weather gets warmer. This may change for MC 1.9, when igloos get added.

**Comment by jredfox** [comment]
ok then it's a 1.9 update feature for that nice but, let's get 1.7.10 done first before porting anything.
