### ISSUE TITLE
0-4fps beta 10's fps =80fps

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#77]
version: beta12
Images: http://i.imgur.com/fwodcJ0.png
Console: http://pastebin.com/U1VGNZJ7
when I create a world I can do nothing because I get 0-4fps.  I can not really click anything with the gui as it lags. I am on 2g of ram.  It is something you added or edited and I don't know why.

**Comment by TheWeatherPony** [comment]
Traced to custom temperature code. Working on cleaning it up.

**Comment by TheWeatherPony** [comment]
Cleaned up the lag, and the download is swapped.
