### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#8]
Have no clue why this occurs
http://pastebin.com/3X7eMPTR

**Comment by TheWeatherPony** [comment]
Already fixed for future versions.

**Comment by jredfox** [comment]
ok sorry it looked slightly different to me.

**Comment by TheWeatherPony** [comment]
Top 10 lines of the stack trace were the same.
Regardless, the issue was already fixed for future versions.
