### ISSUE TITLE
Dimensional Exception ticking world Incompatibility

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#81]
Version: beta12b
AetherII Dungeon Dimension: http://pastebin.com/nMQKU1pF

Aetherii seemed to work well with the seasons mod until you go to the dungeon dimension which has a ticking type of error.  It crashes as soon as you click enter dungeon.

**Comment by TheWeatherPony** [comment]
Same basic cause as #80.

**Comment by TheWeatherPony** [comment]
Closed with same reasoning as #80.
