### ISSUE TITLE
Galacticraft/More Planets Ticking Memory Connections@Thermometer 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#82]
Version: beta12b
Crash Report: http://pastebin.com/JVkGtysJ

Galacticraft and More planets both crash with the season mod if you go to one of there planets/dimensions and right click with the seasons thermometer. It has a ticking memory connection

**Comment by TheWeatherPony** [comment]
Same basic cause as #80.

**Comment by TheWeatherPony** [comment]
Taking another look, this is actually a duplicate of another in #80 (Galacticraft/More Planets)
