### ISSUE TITLE
Snow Has Block Physics

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#83]
Version: Beta12b 
Status: Unknown if in the latest update. I don't seem to have access to the latest url for it.  
Video: https://www.youtube.com/watch?v=MkpNs-2gC1Q
Log: http://pastebin.com/AM5PZt98

Snow has block physics like a block physic mod was instead but, only applies to snow.  instead of air collapsing snow it just drops like sand and gravel without animation straight to the nearest block below.  I have provided a video and a log of the game. I didn't see anything unusual in the log during the event  however, the log might still yield something.

**Comment by TheWeatherPony** [comment]
The log won't yield anything as this is the currently intended behavior. I will change this behavior to not be instant when I do the next overhaul needed for more idealistic snow, which I was already planning on doing.

**Comment by jredfox** [comment]
is falling snow intended?  I would like an option in the config so you can enable snow collapsing by air like you said you would do after I first reported that bug.  I would like it off by default however it's up to you if you want to keep it on by default.  Adding an animation would be a good idea for snow falling for each and every tile variable.

**Comment by TheWeatherPony** [comment]
Snow falling is intended - it is a significant improvement over vanilla, where the snow just vanishes (imagine having 5m snow banks, and being able to clear them just by touching the ground under them - totally unrealistic). Having the snow fall instantaneously may not be perfect, but it's still an improvement. Making the snow fall non-instantaneously is a planned addition.
The logic that collapses the snow instantly is part of the same logic that makes the snow stack into a single block. This part of the snow logic can be disabled by setting the snow logic variable "compress" to false (zero).

**Comment by jredfox** [comment]
yeah well could you at least add in an option in a config to make snow behave like vanilla for it collapsing in air?

**Comment by TheWeatherPony** [comment]
But vanilla doesn't collapse in the air - it simply dematerializes out of existence.
If there isn't already a setting for making it vanish into nothingness, then I'll make sure to add one.

**Comment by jredfox** [comment]
ok.  make sure it's a config option because, snow having physics is intended .
