### ISSUE TITLE
Incompatibility found

### ISSUE THREAD

**Issue by HentaiHamster** [TheWeatherPony/TheSeasonsMod#84]
Hello, I have found an incompatibility with the mod "Immersive Engineering"

I'm on the beta12b....Idk where to downoad 12c   btw

Here is the crash report and full log. If you want/can to check it out. :]

[crash-2016-02-01_07.26.38-client.txt](https://github.com/TheWeatherPony/TheSeasonsMod/files/112461/crash-2016-02-01_07.26.38-client.txt)
[fml-client-latest-1.txt](https://github.com/TheWeatherPony/TheSeasonsMod/files/112464/fml-client-latest-1.txt)

**Comment by jredfox** [comment]
Did you try to add the coremod. Most technical mods have coremods.  

": Examining for coremod candidacy [1.7.2+] KingCore v3.4.2.19.jar
[07:25:51] [Thread-0/DEBUG] [FML/]: Not found coremod data in [1.7.2+] KingCore v3.4.2.19.jar"

it's a 1.7.2 mod. I dought it will work at all by itself. check to see if all the functions work without seasons and or if it even loads at all.  If you can't find anything send it to me.

**Comment by HentaiHamster** [comment]
Hmm. That's weird. It works when I just take out the PML and Seasons mod files and the command line in the profile in the launcher. Plus I also have the KingCore in my mods folder too. 
The weather mod even works with the king core in there too. 

It's only when I put immersive engineering in my mods folder that I get the issue. 
Perhaps KingCore and IE are incompatible as well.

**Comment by TheWeatherPony** [comment]
This is actually the same in nature as #61. My fix is slow coming, but on its way.
Still valid, but closing as a duplicate.

**Comment by HentaiHamster** [comment]
Ahhh okay. I didn't see that. Thank you!!
I will keep following for more info then!

**Comment by TheWeatherPony** [comment]
It's a highly technical issue, so I can understand making a new issue about it. Better to be sure it's reported :)
