### ISSUE TITLE
Compatibility Issues with Forestry?

### ISSUE THREAD

**Issue by Marchingbedlam** [TheWeatherPony/TheSeasonsMod#85]
Minecraft crashes while loading when both Seasons mod and the Forestry mod are installed at the same time. When the Forestry mod is removed from the mods folder Minecraft loads with the seasons mod normally.

Pastebin: http://pastebin.com/XKBvTT4U

**Comment by TheWeatherPony** [comment]
Thank you for letting me know. This is the same nature as #61, though, so I'm going to close this as a duplicate. Still a valid issue, so thank you for reporting it. :)
