### ISSUE TITLE
Temperature Issues [beta12d]

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#89]
Versions; TheSeasonsMod-pre-3.0beta12d.pmlm, [MC]PML-MCP_DEV-1.5 (1).pmlm, [MC]PML-9.3.zip
Images: http://imgur.com/a/eRazs
NBT: http://imgur.com/a/tkmAV
Pml Log: http://pastebin.com/XSHr6M5V
Log: http://pastebin.com/1prrixEY

There are major temperature fluctuations depending on what biome you are in.  For example I am in a prairie  biome and it is 80% humidity when it is -1100% humidity in the forest biome. both of these are in the same seasons summer.  Also it still seems to melt the snow no matter what temperature it is as long as it is spring or summer it seems.  
 I have provided a log with detailed information, details about the situation throw images , nbt also.  If you need any additional information just comment. The Log is tested from only one season from two  different biome with two temperature readings.   I cannot test this any further to see whether or not the issue is a temperature problem , spring defrost problem , or both.  Fix this and I can further test this issue with temperatures/ if the spring defrost is the issue.  do you still have the defrost enabled, and if you do did you disable the melting of the with snow/ice by temperature to?

**Comment by TheWeatherPony** [comment]
The temperatures are customizable, and do not swing that far by default. You have altered the temperatures for a previous and forgotten issue test.
The mod does not yet alter humidity in any way - Minecraft's temperature is based on a non-linear scale, which the mod is representing as a percentage.

The snow is being melted in Spring/Summer regardless of the temperature because you have the legacy setting "SpringDefrost" enabled, which does exactly that. All other melting settings are for the non-legacy, temperature-based melting, which doesn't use the legacy setting in any way.
I have not removed the temperature-based melting code, but you have disabled it according to the pictures of your NBT settings.

Based on what you are saying and showing, I see no bugs/issues.

**Comment by jredfox** [comment]
I had no seasons/settings customized.**it was the default value when I first installed it.**  I think it is like the pml type thing once you get it launched once properly it would launch.  I never touched the configs and I had a fresh .minecraft.**I could test this if you can explain to me where exactly the files all are, for pml , seasons, and mod-dev**.  I don't think you intended the forest to be colder then space so that's was the issue.  there is a list of errors from your intended description then.  **I had not edited any nbt data it all was default**. send me the list of intended default nbt data and then I will send you my defaults but, I first need you to tell me where all of the files are.  just in case there is any other files besides the mod folder.   I can try to retest this in case it had something to do with pml not installing right.

**Comment by TheWeatherPony** [comment]
In that case you have some other mod that is making the normal temperature of the forest be -100 (0.15 is "freezing", desert/nether is 2.0). The only place in this mod that "-100" is used is within the command code for changing the season and season-day as an interim value for the dimension number.

The custom biome temperature settings are stored together with the custom crop settings, and are handled via the same code. By default, the only copy is in the config folder, but settings can be changed to make the settings be in the world/dimensions folders instead/as-well. These settings are in standard json.

You can get new seasonal settings by deleting _both_ the seasonal settings in the world/dimension folder and the config folder.

PML not installing right would have very different manifestations, as it now has nothing to do with Minecraft, other than through the adaptation code (which deals with the LaunchWrapper near-exclusively) and addons/mods.

**Comment by jredfox** [comment]
Edit: I reread your comment.  I don't know if pml installed properly or not but even if it didn't you said it should have because, it popped open for you.  I think it is storeing files elsewhere so it doesn't give you an error if you try on a fresh .minecraft? either that or there is a random chance that without checking keeplauncher open it will crash?
I had a fresh installation. I only had seasons, mod-dev and pml (**if you looked at the pictures I only had 5 mods**). I think it is storing some libraries /files elsewhere where I can't find them and then they don't seem to error.  it's the very first installation is what I think that it had an issue.  I just even installed optifine and that's not it either.  **could you check the code for any of the errors I had?  try seeing first if it's only the first instalation then else try looking for tick loops that might cause , a weird random chance.  however if there are files outside the .minecraft that might be why. remember it's not just the temperature issues it's also improper nbt tags to. spring defrost was also on.**

**Comment by TheWeatherPony** [comment]
This mod has configuration files in the config folder (the "Seasons" subfolder) as well as each and every world and dimension folder - both of which are in the .minecraft folder's subfolders. If you're playing on an old world and/or didn't completely delete the config folder, then it's not really a fresh installation with the newest default settings.
Looking more closely at your NBT settings, it kind of looks like you're using default settings from an older edition of the mod, as meltAttempt used to have the default value of 0 as a mistake, but has been fixed to have a correct value of 1/3d, and SpringDefrost now has a default value of false (0). The only two places these two variables are set is in default initialization and loading from NBT - using Eclipse to find usages confirms this.
`private double meltAttempt = 1/3d;`
`boolean SpringDefrost = false;`

As for the temperature, the code for determining the default seasonal value does not differentiate different biomes, and is this:

```
    public static final float getDefaultSeasonalTemperature(BiomeGenBase biome, Season season){
        float normal = biome.temperature;
        switch(season){
        case Spring:
            return 0.751F * normal;
        case Summer:
            return 1.101F * normal;
        case Autumn:
            return 0.726F * normal;
        case Winter:
            return 0.187F * normal;//just cold enough to make it snow in plains biomes
        default:
            throw new RuntimeException();
        }
    }
```

**Comment by jredfox** [comment]
ok if I get another weird error with a fresh installation with messed up temps and nbts I will record it.
