### ISSUE TITLE
Exception while updating neighbours  java.lang.StackOverflowError: Exception while updating neighbours

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#9]
I loaded a new dimension in deeper caves moved around while it was still loading then your mod crashed it.
http://pastebin.com/u3kk5Ky1

**Comment by PitchBright** [comment]
What makes you think Seasons crashed it? I don't see Seasons mod ANYWHERE in the stacktrace. I think this isn't a Seasons issue, and can be closed.

**Comment by jredfox** [comment]
because, it was only with the seasons mod replicated this with taking out the seasons mod and nothing happened. Also talked to the deeper caves guy and he said it was a vanilla bug

**Comment by TheWeatherPony** [comment]
If it's a vanilla bug, then I'm not going to fix it. I've already spent enough time fixing vanilla bugs that were not my problem, especially without thanks/recognition.

**Comment by jredfox** [comment]
no the neighboring updates he said was vanilla you can work around this hopefully .  make it so it doesn't do something to activate the vanilla bug so you don't have to fix this. the link he gave me and the crash didn't say anything about updating neighbors so maby he is mistaking?

**Comment by jredfox** [comment]
https://bugs.mojang.com/browse/MC-32168

**Comment by TheWeatherPony** [comment]
At the bottom of the stack trace, I recognize the code involved belonging to the start of worldgen. I could change the underlying code so that worldgen doesn't occur, if you'd prefer...?

**Comment by jredfox** [comment]
My bad the near last one says java stock overflow while updating neighbors. it doesn't realy happen too often but, it could be linked to the lag which could link to the crash. also it could be linked to the performance being at 1g of the actual amount of ram used

**Comment by TheWeatherPony** [comment]
It's also possible I'm thinking of the wrong section, since there is a lot of code involved and I'm starting to fall asleep.

**Comment by jredfox** [comment]
same here I had to drink to classes of pop to keep awake

**Comment by jredfox** [comment]
I recreated this crash without optifine. It occurs with just deeper caves this isn't your mod.
