### ISSUE TITLE
Winter Biome Decoraters Not Placing Snow/Ice Properly[3beta12d]

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#90]
Version; TheSeasonsMod-pre-3.0beta12d.pmlm, [MC]PML-MCP_DEV-1.5 (1).pmlm, [MC]PML-9.3.zip
Images: http://imgur.com/a/2jRBX

during winter in new chunks it doesn't place snow /ice properly.  It seems to place the snow/ice randomly and very far apart. It worked a couple versions ago such as beta12 and before.  I think you should take a look at the code , log , and images.  The first picture is a picture of no snow in new chunks during winter.  the second picture is of a rare snow patch in a regular taiga biome.

**Comment by TheWeatherPony** [comment]
Modified how one part of world generation code interacts with seasonal temperatures. May fix the problem you describe, but don't show (your link for images goes to a log). This is a change to intended code, so neither the before nor after will appear in any logs.
Requesting information about what you're describing.

**Comment by jredfox** [comment]
lol how did that happen? ok it's fixed. did you get the notification for #36 ? I think I thought up several optimized solutions.

**Comment by jredfox** [comment]
so is this an issue or an intended feature? it is fixed up there. I don't know if you got the notification when I fixed my stupid mistake or not.

**Comment by TheWeatherPony** [comment]
Leave a comment
