### ISSUE TITLE
[Enhancement ] mc has no weather under certain permeters

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#91]
Version: beta12d
Reasons: http://imgur.com/uWwB38k

If it doesn't rain/snow with certain parameters then it would fix #64.  For example let's take the end dimension snowing but, you could prevent that if the parameter said that it had no sky.  I think if you took a look at the weather code for acia/desert biomes you could fix #64.  This is a major enhancement that I think the mod needs to be completed to be 3.0.  I think this should also be configurable to turn it on / off just in case somebody had a dimension with no sky but, wanted seasons in it.  This could tie to dimension blacklist/whitelisting if you would add this.  the seasons would be false and if it initially has no rain for that dimension then if seasons is disabled whitelist/blacklist it will be like the desert weather with no rain/snow.

**Comment by TheWeatherPony** [comment]
Related issue fixed - a missing ! (not symbol) in part of the snow code. Problem stems from rain and snow being the same thing in some areas, but not the same thing in others. May fix #64, but also may not.
Leaving open as a feature request

**Comment by jredfox** [comment]
It's a blueprint idea for you. you don't have to do exactly what I said.

**Comment by jredfox** [comment]
Maybe you could fix this issue by getting the world's obj and detecting if it has a sky or not based then, check defaults , finally override the world if it can snow/rain in that area based on if it has a sky (a world obj boolean).  

How are you overriding the world to do snow/rain on where it doesn't by default anyways. I think if you ask that question the solution to this issue will be simple.

**Comment by jredfox** [comment]
I see no point in overriden vanilla's storms when you could just use some byte code manipulation with forge or possibly use pml to override the snow statement that is causing these bugs as you have stated previously
