### ISSUE TITLE
Small Bug about world titles.

### ISSUE THREAD

**Issue by justin8e8** [TheWeatherPony/TheSeasonsMod#94]
Just a small bug I found but apparently this mod causes the game to crash if you start up a world with a (?) in its name. nothing too important.

**Comment by jredfox** [comment]
is the folder called "?" or is the world name called "?" . "?" are not supported by windows in file names

**Comment by justin8e8** [comment]
Specifically the world was named Vat? I also tried an instance with ??? And
it appeared no matter what was the folder name when the world had a ? In it
it would crash

**Comment by TheWeatherPony** [comment]
Fixed in the 1.8.9 code a day and a half ago; went back in to the 1.7.10 code and redid the changes there today.
(Fixed for all future versions.)
