### ISSUE TITLE
<Idea> could the latest update of the season mod could work with 1.7.10?

### ISSUE THREAD

**Issue by VirtualGaming1** [TheWeatherPony/TheSeasonsMod#96]
Hi are there a way that you could have it working with minecraft 1.7.10? because I would like to try it in mod pack that is in 1.7.10. if not i can see what mods that is up to that minecraft version.

**Comment by TheWeatherPony** [comment]
The next version of the mod will be "pre-3.0 beta13b" and will be for 1.7.10. It will be a partial back-port of the applicable important changes made in pre-3.0 beta13 for 1.8.9, as well as the things that were not applicable to 1.8.9 or managed to sneak in after I started the port. In addition, it will contain many additional bugfixes, most of which will be ported over to the 1.8.9 line for that MC version's next release ("pre-3.0 beta14).
