### ISSUE TITLE
<Crash Report> Crashing when trying (i think) to edit a sapling

### ISSUE THREAD

**Issue by VirtualGaming1** [TheWeatherPony/TheSeasonsMod#97]
Here is a crash report of the game with my close-beta modpack. (Including Weather2)
[crash-2016-08-08_03.27.30-server.txt](https://github.com/TheWeatherPony/TheSeasonsMod/files/406373/crash-2016-08-08_03.27.30-server.txt)

**Comment by TheWeatherPony** [comment]
Fixed for future versions of the 1.8.9+ line.

**Comment by VirtualGaming1** [comment]
Ok can not wait for it to come out
