### ISSUE TITLE
[Crash] When trying to change color on plants

### ISSUE THREAD

**Issue by VirtualGaming1** [TheWeatherPony/TheSeasonsMod#99]
here is the crash report. when the client side try to change the color on plants
[crash-2016-08-20_19.11.10-client.txt](https://github.com/TheWeatherPony/TheSeasonsMod/files/428585/crash-2016-08-20_19.11.10-client.txt)

**Comment by TheWeatherPony** [comment]
Made a workaround: if the leaf block doesn't properly provide an array of String-names from the vanilla method that queries such information, then my code treats the leaf block like it does non-leaf blocks when forming the name for the coloring.
Fixed.

**Comment by VirtualGaming1** [comment]
ok is this in the next update? because i really want to use this in my modpack along with Local Weather mod (Weather2 mod)
